### ISSUE TITLE
Evaluate responses for POST/PUT APIs

### ISSUE THREAD

**Issue by Shreya-7** [abhiandthetruth/wardrobe-api#8]
Should these APIs return the created/modified resources? Both from an API design perspective AND ease of frontend as it would reduce the number of GET calls.
Also POST should definitely return the created resource otherwise what will we GET ;_;
Currently the create item endpoint doesn't return the item - we need to fix the routes

**Comment by abhiandthetruth** [comment]
The create item does return the Id, right?

**Comment by Shreya-7** [comment]
nope, null response. the python function is also type-hinted to return `None`.

**Comment by Shreya-7** [comment]
https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.1 definitely return the entire created resource for POST calls, but more lenient for PUT.
Let's modify the contract to return the entire resource to save round trip calls to the server to GET the information.
