### ISSUE TITLE
Update models to be atomic and to use all enums

### ISSUE THREAD

**Issue by Shreya-7** [abhiandthetruth/wardrobe-api#9]
- many fields are open-ended strings, let's change these to return enums for more safety
- the categories field has to be re-evaluated, it may need to be broken down into category and sub-category

**Comment by abhiandthetruth** [comment]
I support, category breakdown for sure

**Comment by Shreya-7** [comment]
not the rest? :)

**Comment by abhiandthetruth** [comment]
Nhi category thoda immediate requirement bs. Can do both independently ig

**Comment by abhiandthetruth** [comment]
Decision is to add another field to represent parent category `kind`
